# Generated by Django 4.2.6 on 2023-11-06 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_rename_owner_vote_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="poll_text",
            new_name="text",
        ),
    ]
