# Generated by Django 4.2.6 on 2023-11-06 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_rename_poll_text_poll_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice_text",
            new_name="text",
        ),
    ]
