# Generated by Django 4.2.6 on 2023-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_choice_text_choice_text'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='polls_vote_user_id_4f723f_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['survey'], name='polls_vote_survey__fb6a08_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'choice'], name='polls_vote_poll_id_28ef09_idx'),
        ),
    ]
