# Generated by Django 4.2.6 on 2023-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_vote_polls_vote_user_id_4f723f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='original_choice_text',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
