# Generated by Django 4.2.6 on 2023-12-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_vote_original_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='original_choice_text',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
