# Generated by Django 4.2.6 on 2023-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_vote_choice_alter_vote_original_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='original_choice_text',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
