# Generated by Django 4.2.6 on 2023-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_at'], name='surveys_sur_created_9f7bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['title'], name='surveys_sur_title_97c94a_idx'),
        ),
    ]
