# Generated by Django 4.2.6 on 2023-12-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_surveys_sur_created_9f7bbb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
